### PR TITLE
Some minor coding style changes

### PR DESCRIPTION
**Pull request by princemaple**
@bigardone Thanks for posting this test/demo.
This is great, answered a question that I have been wanting to dig into.

I made some coding style changes, mainly just adding `()`'s to function calls, so they comply with future elixir versions better.

### CODE REVIEW

**Comment by bigardone** [comment]
Hey @princemaple, thank you very much for taking time to review it and add the coding style changes :)
What about the implementation, does it make sense to you?

**Comment by princemaple** [comment]
@bigardone yes, the implementation does make sense to me.
One question though, is the worker for Server only for trying to start it at node startup?

**Comment by bigardone** [comment]
@princemaple exactly! It's for starting it for the first time.The ServerSupervisor will be in charge of starting it from then on.

**Comment by princemaple** [comment]
Hi, with some experiments, I've discovered that you can simply use the standard supervisor way to monitor/restart your server. It turns out that you can monitor and link remote processes, everything just become so easy.

All it took was changing Server to

``` elixir
def start_link do
  case GenServer.start_link(__MODULE__, %{}, name: {:global, __MODULE__}) do
    {:ok, pid} ->
      Logger.info "---- #{__MODULE__} worker started"
      {:ok, pid}
    {:error, {:already_started, pid}} ->
      Logger.info "---- #{__MODULE__} worker already running"
      Process.link(pid)
      {:ok, pid}
  end
end
```

This allows you to ditch the simple_one_for_one supervisor and the node monitor :)

**Comment by bigardone** [comment]
Oh, that totally makes sense! And way more simple 😆 
I will do some tests during the weekend and merge it!
Thank you very much for your time!

**Comment by princemaple** [comment]
No problem :)

**Comment by bigardone** [comment]
I'm actually going to merge this PR and create a new branch with your's, so we have different implementations. I'll mention you in your's, is that ok for you? :)

**Comment by princemaple** [comment]
Sure! Thanks for letting me know.

**Comment by bigardone** [comment]
Cheers!

**Comment by bigardone** [comment]
@princemaple here's your version branch, https://github.com/bigardone/elixir-distributed-supervisors-test/tree/princemaple-version. Feel free to change the solution description if you want :)
Cheers!

**Comment by princemaple** [comment]
Looks about right to me. Cheers!

**Pull request merged**
